# Generated by Django 3.0.3 on 2020-02-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='current_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('L', 'Loaned')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='total_amount',
            field=models.IntegerField(default=1),
        ),
    ]
