# Generated by Django 3.0.3 on 2020-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_auto_20200311_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('paperback', 'Paperback'), ('electronic', 'Electronic')], default='paperback', max_length=11),
        ),
    ]
