# Generated by Django 3.0.3 on 2020-04-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
