# Generated by Django 3.0.3 on 2020-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_auto_20200404_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserved_amount',
            field=models.IntegerField(default=0),
        ),
    ]
