# Generated by Django 3.0.3 on 2020-04-13 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0008_book_reserved_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserver',
            field=models.ManyToManyField(blank=True, related_name='reserverOfBook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrower',
            field=models.ManyToManyField(blank=True, related_name='borrowerOfBook', to=settings.AUTH_USER_MODEL),
        ),
    ]
