# Generated by Django 3.0.3 on 2020-04-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0009_auto_20200413_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.CharField(default='000000000', max_length=13),
        ),
    ]
