# Generated by Django 3.0.3 on 2020-05-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0011_auto_20200423_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.Book')),
                ('file_format', models.CharField(default='', max_length=10)),
                ('link', models.CharField(default='', max_length=100)),
            ],
            bases=('bookshelf.book',),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(default='static/bookshelf/standard_cover.png', max_length=200),
        ),
    ]
