# Generated by Django 3.0.3 on 2020-05-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0012_auto_20200502_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='book',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reserved_amount',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reserver',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.Author'),
        ),
        migrations.CreateModel(
            name='PaperBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.Book')),
                ('total_amount', models.IntegerField(default=1)),
                ('current_amount', models.IntegerField(default=1)),
                ('reserved_amount', models.IntegerField(default=0)),
                ('borrower', models.ManyToManyField(blank=True, related_name='borrowerOfBook', to=settings.AUTH_USER_MODEL)),
                ('reserver', models.ManyToManyField(blank=True, related_name='reserverOfBook', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('bookshelf.book',),
        ),
    ]
