# Generated by Django 3.0.3 on 2020-05-10 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0014_auto_20200504_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbook',
            name='to_giveout',
            field=models.ManyToManyField(blank=True, related_name='toGiveOut', to=settings.AUTH_USER_MODEL),
        ),
    ]
